[tool.poetry]
name = "lab04"
version = "0.1.0"
description = ""
authors = ["shahir1775 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
"graphics.py" = "^5.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
